export const configMy = {
    parent: "#usersTable",
    columns: [
      { title: "Ім’я", value: "name" },
      { title: "Прізвище", value: "surname" },
      { title: "Вік", value: "age" },
      { title: "Стать", value: "sex" },
      { title: "Країна", value: "country" },
      { title: "Посада", value: "job" },
      { title: "Хобі", value: "hobby" },
    ],
  };

  export const usersMy = [
    {
      id: 30050,
      name: "Вася",
      surname: "Петров",
      age: 36,
      sex: "male",
      country: "Ukraine",
      job: "developer",
      hobby: "music",
    },
    {
      id: 30051,
      name: "Іван",
      surname: "Васечкін",
      age: 25,
      sex: "male",
      country: "Ukraine",
      job: "developer",
      hobby: "art",
    },
    {
      id: 30052,
      name: "Лідія",
      surname: "Українець",
      age: 32,
      sex: "female",
      country: "Ukraine",
      job: "developer",
      hobby: "sport",
    },
    {
      id: 30053,
      name: "Артур",
      surname: "Богун",
      age: 28,
      sex: "male",
      country: "Ukraine",
      job: "developer",
      hobby: "music",
    },
    {
      id: 30054,
      name: "Артем",
      surname: "Завірюха",
      age: 31,
      sex: "male",
      country: "Ukraine",
      job: "developer",
      hobby: "painting",
    },
    {
      id: 30055,
      name: "Юлія",
      surname: "Штиволока",
      age: 24,
      sex: "female",
      country: "Ukraine",
      job: "developer",
      hobby: "fishing",
    },
    {
      id: 30056,
      name: "Вадим",
      surname: "Буря",
      age: 41,
      sex: "male",
      country: "Ukraine",
      job: "developer",
      hobby: "cooking",
    },
  ];
